---
# tasks file for roles/apache-centos
- name: Install MariaDB RedHat
  yum:
    name:  "{{ item }}"
    state: latest
  loop:
    - mariadb
    - mariadb-server
  when: ansible_facts['os_family'] == "RedHat"

- name: Install MariaDB Debian
  apt:
    name:  "{{ item }}"
    state: latest
  loop:
    - mariadb-client
    - mariadb-server
  when: ansible_facts['os_family'] == "Debian"


- name: Start and enable service
  service:
    name: mariadb
    state: started
    enabled: yes


- name: Configure firewall RedHat
  firewalld:
    service: mysql
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_facts['os_family'] == "RedHat"


- name: Configure firewall Debian
  ufw:
    rule: allow
    port: '3306'
    proto: tcp
    state: enabled
  when: ansible_facts['os_family'] == "Debian"





