---
# tasks file for roles/apache Debian
- name: Install Apache Server
  apt:
    name: apache2
    state: latest
    update_cache: yes


- name: Start and enable service
  service:
    name: apache2
    state: started
    enabled: yes


- name: Configure firewall http
  ufw:
    rule: allow
    port: "{{ item }}"
    state: enabled
  loop:
    - '80'
    - '443'

