---
# tasks file for roles/apache-centos
- name: Install Apache Server
  yum:
    name: httpd
    state: latest

- name: Create virtualhost config directory 
  file:
    path: /etc/httpd/vhost.d
    state: directory
    mode: '0755'
    owner: root

- name: Add virtualhost config directory to httpd.conf
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: IncludeOptional vhost.d/*.conf

- name: Start and enable services
  service:
    name: httpd
    state: started
    enabled: yes


- name: Configure firewall 
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - http
    - https




